[project]
name = "cover-letter-gen"
version = "0.1.0"
description = "AI Cover Letter Generator"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fpdf>=1.7.2",
    "gradio>=5.3.0",
    "httpx>=0.27.2",
    "ollama>=0.3.3",
]
